# Select image from https://hub.docker.com/_/php/
image: php:8.1

# Select what we should cache
cache:
  paths:
    - vendor/

before_script:
  # Install git, postgres and zip library, the php image doesn't have installed
  - apt update -yqq
  - apt install git libpq-dev libzip-dev zip -yqq

  # Install database driver and zip
  - docker-php-ext-install pdo_mysql pdo_pgsql zip

  # Install composer
  - curl -sS https://getcomposer.org/installer | php

  # Install all project dependencies
  - php composer.phar install

services:
  - mysql
  - postgres
